### ISSUE TITLE
some issues for evaluation

### ISSUE THREAD

**Issue by RammusLeo** [lijiaman/chois_release#5]
Hi! I have met some problems during running `final_evaluations.py`:
```
~/chois_release/t2m_eval$ python final_evaluations.py 
Traceback (most recent call last):
  File "final_evaluations.py", line 5, in <module>
    from motion_loaders.model_motion_loaders import get_motion_loader, get_motion_loader_for_chois_eval 
  File "~/chois_release/t2m_eval/motion_loaders/model_motion_loaders.py", line 2, in <module>
    from utils.get_opt import get_opt
ModuleNotFoundError: No module named 'utils.get_opt'
```
Besides, I found that if I need to reproduce the FID and R-pre, there are still some missing files: 
```
/move/u/jiamanli/eccv24_chois/res_npz_files/gt       #Is the gt joints pos saved under this dir?
processed_data/omomo_text_anno_txt_data           #Is the .txt data with one_hot token saved under this dir?
/move/u/jiamanli/github/text-to-motion/glove_840B     #Is the glove data saved under this dir?   
```
I cannot find these data in any links you provided. Could you offer any further data for reproducing the results? Thanks!

**Comment by Mael-zys** [comment]
Hi, did you manage to run this evaluation script? 

Besides, I cannot find this function. Do you know where I can import this?
`from options.train_options import TrainTexMotMatchOptions`

**Comment by RammusLeo** [comment]
Nope:( I still have no idea.

**Comment by lijiaman** [comment]
I just uploaded get_opt.py, we used the code from https://github.com/EricGuo5513/text-to-motion/tree/main , modified to our setting, but most files are unchanged. 

res_npz_files/gt contains 3D joint positions of GT 

For glove, you could refer to this: https://nlp.stanford.edu/projects/glove/ 

For text annotation, please download https://github.com/lijiaman/omomo_release/blob/main/omomo_text_anno.zip

**Comment by Mael-zys** [comment]
Thanks for your reply. 

The text annotation that you provided is a json file in this format:
`{"sub1_clothesstand_000": "Lift the clothesstand, move the clothesstand, and put down the clothesstand."}`

However, for evaluation, the code uses txt file containing both caption and tokens:
```python
# Load .txt file 
txt_path = os.path.join(self.language_anno_folder, seq_name+".txt")
with cs.open(txt_path) as f:
    for line in f.readlines():
        text_dict = {}
        line_split = line.strip().split('#')
        caption = line_split[0]
        tokens = line_split[1].split(' ')
       
        text_dict['caption'] = caption
        text_dict['tokens'] = tokens
        
f.close() 
```
Could you provide these files?

**Comment by HitBadTrap** [comment]
> Thanks for your reply.
> 
> The text annotation that you provided is a json file in this format: `{"sub1_clothesstand_000": "Lift the clothesstand, move the clothesstand, and put down the clothesstand."}`
> 
> However, for evaluation, the code uses txt file containing both caption and tokens:
> 
> # Load .txt file 
> txt_path = os.path.join(self.language_anno_folder, seq_name+".txt")
> with cs.open(txt_path) as f:
>     for line in f.readlines():
>         text_dict = {}
>         line_split = line.strip().split('#')
>         caption = line_split[0]
>         tokens = line_split[1].split(' ')
>        
>         text_dict['caption'] = caption
>         text_dict['tokens'] = tokens
>         
> f.close() 
> Could you provide these files?

Have you addressed this issue? If so, could you provide these txt files?
